language: groovy
jdk:
- openjdk7
sudo: false
before_install:
- export TZ=Europe/Stockholm
- date
- rm -rf ~/.sdkman
- curl -s http://get.sdkman.io | bash
- echo "sdkman_auto_answer=true" > ~/.sdkman/etc/config
- source ~/.sdkman/bin/sdkman-init.sh
- GRAILS_VERSION=`grep '^app\.grails\.version=' ./application.properties | sed -e
  's/^app\.grails\.version=//g'`
- sdk install grails $GRAILS_VERSION || true
before_script:
- GRAILS_VERSION_NUMBER=`echo $GRAILS_VERSION | sed -e 's/\.[0-9]*$//g' -e 's/\.//g'
  | tr -d "\r"`
- echo "GRAILS_VERSION_NUMBER:$GRAILS_VERSION_NUMBER"
- GRAILS_SETTINGS_FILE="travis_grails_settings_new.groovy"
- if [ "$GRAILS_VERSION_NUMBER" -lt "23" ]; then GRAILS_SETTINGS_FILE="travis_grails_settings_old.groovy";
  fi;
- echo "GRAILS_SETTINGS_FILE:$GRAILS_SETTINGS_FILE"
- mkdir -p ~/.grails
- wget -q -O ~/.grails/settings.groovy https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/$GRAILS_SETTINGS_FILE
script:
- grails clean && grails refresh-dependencies --non-interactive && grails prod war
  --non-interactive
deploy:
  provider: releases
  api_key:
    secure: SUHAEmw+pzvobIKExQIfUjD+EyJRs+94q6FbkaWMROa3ThgSTSQ/FUkOalGfckstXGGLzKCp8VNwyRiHYT6i+0PTQapuMhCpiLKek18AO1u8iF8GSjUqeXpHzR4m+LiMcKAfZwrD0ioPViG1oWL8XQK/yHFAVbykhGHj6yGHKvd0/JfmgM3LEgMvTn6DNmU1sI5D3QaKlYCvuUDZ1EElo+YYzMTHDOcmvFtl755PJKB/0WXn7Dq8uGM0p3BBrHHbzmoXX9Dpe8zHTHHfDLrq9U/esguC3/EripzJ3XFdblSQQjmFJfeeDY0ELADe0qsP1Yvk7Q/pcTVKqYKLl2lQh6ysZL6IOpjwknxfmatx/IyBkdqWPUhQXzlMuPVD+cRcmVjxeL0dCdx+sZbYrlR2T5MvL96E1ohp1FNEZzEE4l4QKO5B4ie0MMOvQAqq931eLAezzUTs3TFENu67EBb74bM7nIBK2d7sp9/US4f7ykCMN+16qiFt6oSjD8t2N34rvlMZXwAYSKJG2BQvXrwLKLLkZRy0tsysu70zXbclxaEJnPaA+ncZ9w+Agt+jzbsyrLpzbnywu87ZKoXlMxnEwZr7k2WMPcta0Bo25f0rZOoVSgt3fFb0Mvd4BRvBbZD2yTbSbalL//PZFSF83mnnVnkMUX6UPF6JG8zCvpRjrsM=
  file: "target/ala-images*.war"
  skip_cleanup: true
  overwrite: true
  file_glob: true
  on:
    repo: bioatlas/image-service
    all-branches: true
    tags: true
