--- 
networks: 
  elasticsearch: ~
services: 
  elasticsearch: 
    container_name: elasticsearch
    environment: 
      - cluster.name=docker-cluster
      - discovery.type=single-node
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.0.0"
    networks: 
      - elasticsearch
    ports: 
      - "9200:9200"
      - "9300:9300"
  kibana: 
    container_name: kibana
    depends_on: 
      - elasticsearch
    environment: 
      - SERVER_NAME=kibana.localhost
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTIC_PWD=changeme
      - KIBANA_PWD=changeme
    expose: 
      - "5601"
    image: "docker.elastic.co/kibana/kibana:7.0.1"
    links: 
      - elasticsearch
    networks: 
      - elasticsearch
    ports: 
      - "5601:5601"
    depends_on: 
      - elasticsearch      
version: "2"
