---
networks:
  postgres: ~
services:
  postgresql:
    container_name: postgres-image-service
    image: "postgres:9.6.8-alpine"
    networks:
      - postgres
    ports:
      - "5432:5432"
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
version: "2"
